services:
  broker:
    image: rabbitmq:latest
    hostname: broker
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${STEGA_BROKER_USER}
      RABBITMQ_DEFAULT_PASS: ${STEGA_BROKER_PASS} 
    volumes:
      - broker_data:/var/lib/rabbitmq

volumes:
  broker_data:
